from __future__ import annotations

VALID_TRANSITIONS: dict[str, set[str]] = {
    "FVG_DETECTED": {"FVG_ACTIVE", "REJECTED", "INVALIDATED"},
    "FVG_ACTIVE": {"INVERTED", "EXPIRED", "INVALIDATED", "REJECTED"},
    "INVERTED": {"IFVG_ACTIVE", "REJECTED", "INVALIDATED"},
    "IFVG_ACTIVE": {"WAITING_RETEST", "EXPIRED", "INVALIDATED", "REJECTED"},
    "WAITING_RETEST": {"RETEST_DETECTED", "EXPIRED", "INVALIDATED", "REJECTED"},
    "RETEST_DETECTED": {"WAITING_CONFIRMATION", "INVALIDATED", "REJECTED"},
    "WAITING_CONFIRMATION": {"CONFIRMED", "EXPIRED", "REJECTED"},
    "CONFIRMED": {"ENTRY_ELIGIBLE", "REJECTED", "AMBIGUOUS"},
    "ENTRY_ELIGIBLE": {"ORDER_INTENT", "REJECTED", "EXPIRED"},
    "ORDER_INTENT": {"ORDER_SUBMITTED", "ORDER_REJECTED", "AMBIGUOUS", "REJECTED"},
    "ORDER_SUBMITTED": {"ORDER_PARTIALLY_FILLED", "ORDER_FILLED", "POSITION_OPEN", "ORDER_REJECTED", "ORDER_EXPIRED", "AMBIGUOUS", "RECONCILIATION_REQUIRED"},
    "ORDER_PARTIALLY_FILLED": {"ORDER_PARTIALLY_FILLED", "ORDER_FILLED", "ORDER_REJECTED", "ORDER_EXPIRED", "AMBIGUOUS", "RECONCILIATION_REQUIRED"},
    "ORDER_FILLED": {"POSITION_OPEN", "RECONCILIATION_REQUIRED", "AMBIGUOUS"},
    "POSITION_OPEN": {"TP_FILLED", "STOP_TRIGGERED", "AMBIGUOUS", "RECONCILIATION_REQUIRED"},
    "TP_FILLED": {"POSITION_CLOSED"},
    "STOP_TRIGGERED": {"POSITION_CLOSED"},
    "POSITION_CLOSED": set(),
    "EXPIRED": set(),
    "INVALIDATED": set(),
    "REJECTED": set(),
    "AMBIGUOUS": {"RECONCILIATION_REQUIRED"},
    "RECONCILIATION_REQUIRED": {"ORDER_SUBMITTED", "ORDER_PARTIALLY_FILLED", "ORDER_FILLED", "POSITION_OPEN", "POSITION_CLOSED", "AMBIGUOUS"},
}


class InvalidIFVGTransition(ValueError):
    pass


def validate_transition(from_state: str | None, to_state: str) -> None:
    if not to_state:
        raise InvalidIFVGTransition("empty target state")
    if from_state is None:
        return
    if to_state not in VALID_TRANSITIONS.get(from_state, set()):
        raise InvalidIFVGTransition(f"invalid IFVG transition {from_state} -> {to_state}")
